### PR TITLE
1. Added checking for writing and reading Null Class and Collection Prop...

### PR DESCRIPTION
**Pull request by GoorMoon**
...erty.

2. Added checking for reading _NOT_PARSED_ value

### CODE REVIEW

**Comment by GoorMoon** [comment]
gohsianghwee,
Like you ask in issues #58, #59 created this PR.
I checked this but some test cases are failed, i need more time to investigate this.

**Comment by gohsianghwee** [comment]
Hi @GoorMoon,

Sure. Please let me know if you need more info.

**Comment by gohsianghwee** [comment]
Hi @GoorMoon ,

I am not sure about the difference between LINKLIST and LINKBAG as I don't use it currently and my usage still pretty much on Document instead of Graph. However, when the object is null but being instantiated, we will have problem to know whether we save the object in purpose or not. Is there any workaround? Thanks.

**Comment by GoorMoon** [comment]
@gohsianghwee ,
LINKBAG is a tree like structure, main purpose is to fetch only root node and lazy load remaining nodes then requested. 
A big problem with LINKRIDBAG is additions round-trip to the server.  
Another problem driver must manage state for such fields and send to the server changes only.
http://www.orientechnologies.com/docs/last/orientdb.wiki/RidBag.html

**Comment by calebbriggs** [comment]
@GoorMoon since the rewrite to DNX Core RC2 We encourage you to pull down the latest and resubmit this pull request, but we are going to close this pull request

**Pull request closed without merging**
