### PR TITLE
Fix bug to allow record strings with embedded documents to be deserialized correctly.

### PR DESCRIPTION
**Pull request by roberttaylor26**
I noticed that when I tried to read documents containing embedded documents that the embedded documents were not deserializing correctly so I fixed this bug. I've added unit tests as I couldn't see any around the RecordCSVSerializer class.

### CODE REVIEW

**Comment by GoorMoon** [comment]
Hi @roberttaylor26,
Thank you for contributing driver for now has so many breaking changes this why i can't merge your PR. I will do this in the feature.

**Comment by roberttaylor26** [comment]
Hi, yeah I noticed 5 or 6 failing tests when I cloned the repo. If these tests were green would you be able to merge then or do you know about other issues? If I get some free time I might help out with getting these tests green unless you beat me to it :-)

**Comment by GoorMoon** [comment]
We are talking about Driver that official supported by orientdb team and i contribute to that driver.
Driver Should support from 1.7.x up to 2.0 (should be released soon) it's should support all STORAGE Types Memory and Plocal. I would love if you can help me with issues opened here. But them need to be checked on all versions of orientdb.

**Comment by roberttaylor26** [comment]
Just to clarify I cloned https://github.com/orientechnologies/OrientDB-NET.binary.git and ran the tests (without making any changes) and 5 fail with what look to be genuine (non environment setup) failures when running against OrientDB 1.7.10. I just wanted to make sure that this is what you were referring to above as the " breaking changes" that were preventing you from merging my pull request?  I'm keen to get my change merged and to have a version of the driver (including my change) available in nuget so basically want to know what I can do to make/help this happen?

Just to confirm, https://github.com/orientechnologies/OrientDB-NET.binary.git is the official driver repo isn't it?

**Comment by GoorMoon** [comment]
Yes this is official driver repository.

**Comment by roberttaylor26** [comment]
Thanks :-)

**Comment by GoorMoon** [comment]
I reverted changes still have issues

**Comment by roberttaylor26** [comment]
Hmm, why don't you run the tests in master and note which tests fail. Then
merge my changes in and see if any other tests fail then. If not then it's
probably safe to merge my changes into master (especially if the current
broken tests are around adding edges to graphs, which are probably due to
bad binary encoding that does not match what orientdb is expecting.)

**Comment by GoorMoon** [comment]
Sorry accidentally pushed the changes to github.
I look at how you can get your changes into the code.
Can you please open a new PR?
Sorry again.

**Comment by roberttaylor26** [comment]
Yeah no problem, I can do that tomorrow I'm enjoying the rare luxury of
being in a holiday home with no computer at the moment :-)

**Comment by GoorMoon** [comment]
Look this again and found bug in your test case.
according https://github.com/orientechnologies/orientdb/wiki/Record-CSV-Serialization

```
Embedded documents are enclosed by parenthesis ( and ) characters. E.g. (name:"rules"). 
Note: before SVN revision 2007 (0.9.24-snapshot) only  characters were used to begin and end the embedded document.*
```

correct your test case and all test complete successfully
Could you please check this ?

**Comment by roberttaylor26** [comment]
Thanks, I suspect that I named my tests in a confusing manner by mentioning
'embedded documents' and what I really meant was 'embedded maps'. Il
correct this.

**Comment by roberttaylor26** [comment]
Hi,

I've just created another pull request as requested after making some more
very minor changes.

Thanks,
Rob

**Pull request merged**
